### PR TITLE
Added 'directionsMode' prop to options

### LINKED ISSUE #152: Add support work specifying directions mode: walk, car, bike
Could that be another generalised property that gets converted individually for each provider?

### PR DESCRIPTION
**Pull request by erickriva**
Options now have a 'directionsMode' property.
Values are `car`, `walk`, `public-transport`  or `bike`

'Bike' mode doesn't work on Apple Maps.

Added example too.

Documentations:
[Apple Maps](https://developer.apple.com/library/archive/featuredarticles/iPhoneURLScheme_Reference/MapLinks/MapLinks.html#//apple_ref/doc/uid/TP40007899-CH5-SW1) (`dirflg` prop)
[Google Maps](https://developers.google.com/maps/documentation/urls/get-started#directions-action) (`travelmode` prop)

---

Fixes #152

### CODE REVIEW

**Comment by tschoffelen** [comment]
Hi, thanks for this @erickriva!

The only thing missing is adding this new prop to the README.

**Comment by tschoffelen** [comment]
Closes #195

**Comment by erickriva** [comment]
@tschoffelen README updated.
After PR approval, in how much time do you think a new version can be out?

**Review by tschoffelen — APPROVED** [review]
Awesome work! I'll get a new version out in the next 15 minutes.

**Comment by tschoffelen** [comment]
Released as `react-native-map-link@2.8.0`

Thanks again for your contribution!

**Pull request merged**
