### PR TITLE
Fix: Apple Maps currently searching for the `title` even though `latitude` and `longitude` are provided

### PR DESCRIPTION
**Pull request by jorgerodrigues**
Changing the search from using `sll` to use only `ll` as correctly pointed out here #222 
According to apple docs `sll` will be used to determine the area where a search will be performed where, `ll`
 will be used for centering upon a search. 

These are two very different use cases, where `ll` is the appropriate method when we are using the `showLocation` option. 
To achieve a behavior similar to what `sll` provides we might want to have a new exported function from the lib since it is a different case.
https://developer.apple.com/library/archive/featuredarticles/iPhoneURLScheme_Reference/MapLinks/MapLinks.html

### CODE REVIEW

**Comment by trooperandz** [comment]
Confirmed that this update works for me as well; should probably be merged.

**Comment by jorgerodrigues** [comment]
@tschoffelen

**Comment by tschoffelen** [comment]
Is it likely this will break anything for existing users? I.e. should this be released as a minor version or as a patch? Not sure if I understand the exact impact.

**Comment by jorgerodrigues** [comment]
> Is it likely this will break anything for existing users? I.e. should this be released as a minor version or as a patch? Not sure if I understand the exact impact.

Unlikely. The app right now is broken and this change is mostly to revert it the proper behaviour where `lat` and `lon` are used for searching while the `title` is only used for the title. Right now, the title superseeds the latitude and longitude which yields a wrong search result

**Comment by tschoffelen** [comment]
Makes sense! If you are able to fix the tests, I'm happy to merge this and release a new version this evening.

**Review by tschoffelen — APPROVED** [review]

**Comment by tschoffelen** [comment]
Thanks for your contribution!

Released to NPM as `react-native-map-link@2.9.4`

**Pull request merged**
