### PR TITLE
Bugfix - for truckmap url protocall

### PR DESCRIPTION
**Pull request by mgithubmessier**
- Sorry to duplicate [a PR](https://github.com/flexible-agency/react-native-map-link/pull/216), but we want this functionality ASAP

### CODE REVIEW

**Comment by mgithubmessier** [comment]
@tschoffelen this is a duplicate of https://github.com/flexible-agency/react-native-map-link/pull/216, but with the unit test fixes -- my company just wanted the changes to support this quickly

**Review by tschoffelen — APPROVED** [review]
Looks great, thanks!

**Comment by tschoffelen** [comment]
Released to NPM as `react-native-map-link@2.9.3`

**Comment by naftalibeder** [comment]
@mgithubmessier Sorry about that, thanks for picking up the ball!

**Pull request merged**
